//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_uye
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_uye()
        {
            this.tbl_oduncalma = new HashSet<tbl_oduncalma>();
        }
    
        public int uyeID { get; set; }
        public string uyeADSOYAD { get; set; }
        public string uyeTEL { get; set; }
        public string uyeMail { get; set; }
        public string uyeUsername { get; set; }
        public string uyePassword { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_oduncalma> tbl_oduncalma { get; set; }
    }
}
