//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_kitap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_kitap()
        {
            this.tbl_oduncalma = new HashSet<tbl_oduncalma>();
        }
    
        public int KitapID { get; set; }
        public string KitapAD { get; set; }
        public string Yazar { get; set; }
        public string Yayınevi { get; set; }
        public Nullable<short> SayfaSayisi { get; set; }
        public Nullable<int> Türü { get; set; }
        public string Bilgi { get; set; }
        public string Durum { get; set; }
        public byte[] KitapResim { get; set; }
    
        public virtual tbl_kategorikitap tbl_kategorikitap { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_oduncalma> tbl_oduncalma { get; set; }
    }
}
