//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class kutupsenlEntities : DbContext
    {
        public kutupsenlEntities()
            : base("name=kutupsenlEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_kategorikitap> tbl_kategorikitap { get; set; }
        public virtual DbSet<tbl_kitap> tbl_kitap { get; set; }
        public virtual DbSet<tbl_oduncalma> tbl_oduncalma { get; set; }
        public virtual DbSet<tbl_uye> tbl_uye { get; set; }
    }
}
